@echo off
chcp 65001 >nul
title Alien AI Trader — Package for Distribution
color 0B

echo.
echo  +----------------------------------------------------------+
echo  ^|   👽  ALIEN AI TRADER — Package for Distribution        ^|
echo  ^|   Builds AlienAITrader-Install.zip on your Desktop      ^|
echo  +----------------------------------------------------------+
echo.
echo  This creates a clean distributable ZIP that includes:
echo    - LAUNCH.bat          (main entry point, autorun target)
echo    - INSTALL.ps1         (full installer with tutorial)
echo    - autorun.inf         (CD/DVD autorun definition)
echo    - splash\index.html   (animated spinning disc UI)
echo    - make_icon.py        (generates the alien icon)
echo    - setup_wizard.py     (interactive API key wizard)
echo    - START.bat           (one-click launcher after install)
echo    - All source files    (dashboard.py, trading_engine.py, etc.)
echo    - README.md           (full documentation)
echo.
echo  Excluded (private / generated):
echo    - .venv               (rebuilt by installer on each machine)
echo    - keys.bat / .env     (private API keys — never distribute!)
echo    - trading_settings.json (your personal settings)
echo    - __pycache__         (auto-generated bytecode)
echo    - .git / .claude      (internal tooling)
echo    - backups, *.bak, legacy and any standalone apps
echo.

set DEST=%USERPROFILE%\Desktop\AlienAITrader-Install.zip
if exist "%DEST%" del /f /q "%DEST%"

echo  Building package...
echo.

powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$src = '%~dp0'; $src = $src.TrimEnd('\'); " ^
  "$tmp = Join-Path $env:TEMP 'AlienAITrader-Build'; " ^
  "if (Test-Path $tmp) { Remove-Item $tmp -Recurse -Force }; " ^
  "New-Item -ItemType Directory -Path $tmp | Out-Null; " ^
  "$dst = Join-Path $tmp 'Alien_AI_Trader'; " ^
  "robocopy $src $dst /E " ^
    "/XD '.venv' '__pycache__' '.git' '.claude' '.github' 'installer' 'legacy' " ^
        "'black_box' 'agent ADAM' 'adam_agent' 'user_cloud' 'backup files zipped' " ^
        "'Extractor zip location' " ^
    "/XF 'keys.bat' '.env' 'trading_settings.json' 'config.json' '*.bak' " ^
        "'*.code-workspace' 'export_render_env.*' '*.pyc' '*.pyo' '*.db' " ^
        "'*.sqlite3' '*.log' " ^
    "/NFL /NDL /NP /NJS /NJH | Out-Null; " ^
  "New-Item -ItemType Directory -Path (Join-Path $dst 'installer') | Out-Null; " ^
  "Compress-Archive -Path $dst -DestinationPath '%DEST%' -Force; " ^
  "Remove-Item $tmp -Recurse -Force; " ^
  "Write-Host '  Package saved to: %DEST%'"

echo.

if exist "%DEST%" (
    echo  +----------------------------------------------------------+
    echo  ^|  ✔  Package created successfully!                       ^|
    echo  +----------------------------------------------------------+
    echo.
    echo  File: %DEST%
    echo.
    echo  To distribute:
    echo    DOWNLOAD  → Upload the ZIP to your website / Google Drive / GitHub Releases
    echo               Users extract the folder and double-click LAUNCH.bat
    echo.
    echo    CD / DVD  → Burn the contents of the ZIP (not the ZIP itself)
    echo               to a disc. Windows will autorun LAUNCH.bat on insert.
    echo               The disc label and icon come from autorun.inf.
    echo.
    echo    USB DRIVE → Copy the contents of the ZIP to the drive root.
    echo               Users open the drive and double-click LAUNCH.bat.
    echo.
    echo  How recipients install on their machine:
    echo    1. Insert disc  -or-  extract ZIP  -or-  open USB drive
    echo    2. Double-click LAUNCH.bat  (or wait for autorun on disc)
    echo    3. Choose [1] INSTALL from the menu
    echo    4. Follow the step-by-step wizard (Python install, API keys, shortcut)
    echo    5. App launches automatically and opens at http://localhost:5000
    echo.
) else (
    echo  [ERROR] Package creation failed. Check that PowerShell is available.
)

pause

:: Built by Troy Walker of T-Dub's Apps — 2026
